default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  database: <%= ENV["POSTGRES_NAME"] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>